"""Real weekly plans — production IT ops + portfolio projects. Used by generate_weeks.py."""

from __future__ import annotations

# Each week: title + days (mon–sun) with guide, steps, resources; optional proveLink on sat/sun


def _day(section: str, label: str, guide: str, steps: list[str], resources: list[str], prove_link: str | None = None) -> dict:
    d: dict = {"section": section, "label": label, "guide": guide, "steps": steps, "resources": resources}
    if prove_link:
        d["proveLink"] = prove_link
    return d


WEEK_PLANS: list[dict] = [
    # ── Week 1: Pick the friction candidate ──
    {
        "title": "Ops friction inventory — pick your automation target",
        "days": {
            "mon": _day("friction", "Friction",
                "Quantify what IT actually handles manually at production IT.",
                [
                    "Export or count IT service desk tickets (last 30 days) by category: access, SaaS, MDM, onboarding",
                    "Note Slack IT support channel or governance app volume — real counts only",
                    "Rank top 3 by frequency + time spent (your estimate, not invented %)",
                    "Pick ONE candidate for this unit: access request OR ticket triage",
                ],
                ["CONTEXT.md", "study-notes/weeks/week-01-friction-inventory.md"]),
            "tue": _day("workflow", "Workflow",
                "Sketch intake → approval → action for your chosen friction.",
                [
                    "Draw current manual path (who submits, who approves, who executes)",
                    "Mark where Slack intake workflow or workflow automation already automates similar steps",
                    "Add HITL gate before any Okta write or Jira state change",
                    "Output: one-page workflow diagram (Excalidraw/Mermaid OK)",
                ],
                ["study-notes/weeks/week-01-friction-inventory.md", "phases/phase-1/README.md"]),
            "wed": _day("identity", "Identity",
                "Map identity touchpoints for the candidate workflow.",
                [
                    "List Okta groups / access governance policies involved (pattern names, not secrets)",
                    "Document who can approve grants (manager? app owner? IT?)",
                    "Define audit fields: requester, approver, ticket_id, groups_before/after, timestamp",
                    "Note: agent future — read-only Okta MCP vs write via access governance API",
                ],
                ["projects/02-okta-mcp-server/", "study-notes/wif-agent-identity-design.md"]),
            "thu": _day("agent", "Agent",
                "Decide where an agent helps vs stays deterministic.",
                [
                    "Deterministic: Okta group add, Jira transition, access governance API call",
                    "Agent-suitable: classify ticket intent, KB lookup, route to right queue",
                    "Review projects/01-it-helpdesk-agent — RAG for VPN/MDM/SSO questions",
                    "Write 3 example prompts the agent would handle vs 3 it must escalate",
                ],
                ["projects/01-it-helpdesk-agent/README.md", "projects/02-okta-mcp-server/README.md"]),
            "fri": _day("measure", "Measure",
                "Baseline before automation — numbers you can actually collect.",
                [
                    "Record current weekly ticket count for your chosen category",
                    "Estimate manual minutes per request (sample 5 tickets, average handling time)",
                    "Decide where data lives: Jira fields, BigQuery export, workflow automation execution log",
                    "Do NOT invent deflection % — write the measurement plan only",
                ],
                ["tracker/months.json Month 1 rubric"]),
            "sat": _day("prove", "Prove",
                "Run the portfolio helpdesk agent against real runbook questions.",
                [
                    "Clone repo, set up projects/01-it-helpdesk-agent per README",
                    "Run 5 queries: 3 IT runbook questions + 2 identity lookups via Okta MCP",
                    "Screenshot or log: which answered correctly vs escalated",
                    "Save notes to study-notes/weeks/week-01-prove-log.md",
                ],
                ["projects/01-it-helpdesk-agent/", "README.md"],
                "projects/01-it-helpdesk-agent/"),
            "sun": _day("prove", "Prove",
                "Polish friction inventory draft.",
                [
                    "Complete study-notes/weeks/week-01-friction-inventory.md from workbook output",
                    "Link workflow diagram from Tue",
                    "One paragraph: why this candidate fits AI Systems portfolio narrative",
                ],
                ["study-notes/weeks/week-01-friction-inventory.md"],
                "study-notes/weeks/week-01-friction-inventory.md"),
        },
    },
    # ── Week 2: Map against shipped automation ──
    {
        "title": "Compare candidate to shipped Slack + workflow automation patterns",
        "days": {
            "mon": _day("friction", "Friction",
                "Deep-dive your chosen category with real examples.",
                ["Pull 5 anonymized ticket examples", "Note repeat questions vs one-offs", "Identify approval delays (waiting on manager/app owner)", "Tag each: automatable / agent-assist / human-only"],
                ["IT service desk samples"]),
            "tue": _day("workflow", "Workflow",
                "Reverse-engineer Slack intake workflow as reference architecture.",
                ["Document trigger (Slack slash/modal), validation, Jira create/update", "List failure modes you've seen in prod", "Gap analysis: what's missing for your candidate workflow?", "Reuse patterns: structured intake, idempotent Jira writes"],
                ["Shipped Slack intake workflow (internal)", "projects/03-agentspace-rollout/"]),
            "wed": _day("identity", "Identity",
                "access governance access-request path (production pattern).",
                ["Map access governance request → approval → Okta provision flow you operate", "Note SCIM vs manual group adds", "Where would audit log hook in for agent workflow?", "Compare to consulting offer (b) in CONTEXT.md"],
                ["CONTEXT.md consulting (b)", "Okta + access governance production"]),
            "thu": _day("agent", "Agent",
                "Wire agent concepts to workflow automation vs ADK split.",
                ["workflow automation: deterministic webhooks, schedules, approval branches", "ADK/helpdesk agent: NL triage + RAG", "Define handoff: agent classifies → workflow automation executes approved action", "Draft sequence diagram agent → HITL → access governance/Okta"],
                ["workflow automation shipped workflows", "projects/01-it-helpdesk-agent/"]),
            "fri": _day("measure", "Measure",
                "Approval latency baseline.",
                ["For 5 access/triage tickets: time from open → first human action → resolved", "Note bottlenecks (approver OOO, wrong queue, missing info)", "Metric candidates: approval_latency, reopen_rate"],
                ["Jira timestamps"]),
            "sat": _day("prove", "Prove",
                "Workflow diagram v2 with shipped-pattern callouts.",
                ["Update Tue diagram with Slack app + workflow automation reuse notes", "Commit to study-notes/", "Add to portfolio narrative draft"],
                ["study-notes/weeks/week-02-workflow.md"]),
            "sun": _day("prove", "Prove",
                "Review projects/04-prompt-playbooks for intake wording.",
                ["Read projects/04-prompt-playbooks/teams/it-ops.md", "Draft intake form fields for your workflow (Slack modal or form)", "Align language for non-technical requesters"],
                ["projects/04-prompt-playbooks/"]),
        },
    },
    # ── Week 3: SaaS + MDM friction slice ──
    {
        "title": "SaaS onboarding + MDM friction (MDM platform fleet)",
        "days": {
            "mon": _day("friction", "Friction",
                "Expand inventory: SaaS onboarding + macOS requests.",
                ["Add MDM ticket types to friction list (~600 device fleet context)", "SaaS onboarding: app provisioning, SSO assignment, license", "Cross-check: overlaps with access-request candidate?", "Update study-notes/week-01-friction-inventory.md"],
                ["MDM platform MDM (production)"]),
            "tue": _day("workflow", "Workflow",
                "Multi-step onboarding workflow draft.",
                ["Trigger: new hire or role change ticket", "Steps: Okta groups → SaaS SSO → MDM profile (if applicable)", "HITL: manager confirms role before group grants", "Reference endpoint control service if endpoint/cloud touchpoints involved"],
                ["endpoint control service GCP Cloud Run (shipped)", "projects/06-cipher/ (future ABAC mover)"]),
            "wed": _day("identity", "Identity",
                "Joiner/mover group patterns.",
                ["Document functionalTeam / ABAC group naming you use (pattern level)", "Read projects/06-cipher/SHIP-PLAN.md — how CIPHER will compute deltas", "Interview frame: CIPHER in development, not shipped", "List groups that must NEVER be agent-writable"],
                ["projects/06-cipher/SHIP-PLAN.md"]),
            "thu": _day("agent", "Agent",
                "Helpdesk agent for MDM/SSO questions.",
                ["Test agent on: VPN, MDM platform enrollment, Okta Verify troubleshooting", "Document 3 runbook gaps to add to RAG corpus", "Escalation rule: device compliance → human MDM admin"],
                ["projects/01-it-helpdesk-agent/"]),
            "fri": _day("measure", "Measure",
                "Onboarding workflow timing.",
                ["Sample 3 recent onboarding tickets — hours to complete all steps", "Identify parallelizable vs sequential steps", "Metric: steps_automated vs manual"],
                []),
            "sat": _day("prove", "Prove",
                "Add 3 runbook snippets to helpdesk agent test corpus.",
                ["Extend local runbook markdown or note paths for RAG", "Re-run 3 failing queries from Week 1", "Log results in study-notes/"],
                ["projects/01-it-helpdesk-agent/"]),
            "sun": _day("prove", "Prove",
                "Consolidate Month 1 prep for capstone week.",
                ["Checklist: friction list, workflow v2, baseline metrics, agent test log", "Gap list for Week 4 capstone"],
                ["tracker/months.json Month 1"]),
        },
    },
    # Week 4 = capstone (handled by months.json)
    {"title": "Month 1 capstone — friction map + workflow diagram", "capstone": True},
    # ── Week 5–7: Identity-scoped automation + CIPHER ──
    {
        "title": "Document production access governance/Okta access grant flow",
        "days": {
            "mon": _day("friction", "Friction", "Access-request volume and pain points.",
                ["Quantify access governance/Okta requests per week (real count)", "Categories: new app, role change, time-bound access", "Note denied/expired requests — rework friction"],
                ["access governance production"]),
            "tue": _day("workflow", "Workflow", "Production access grant sequence.",
                ["Document: request → manager approval → provisioning → confirmation", "Where Slack or email notifications fire", "Compare to consulting offer (b) deliverable outline"],
                ["CONTEXT.md consulting (b)"]),
            "wed": _day("identity", "Identity", "Least-privilege grant design.",
                ["Map approval matrix by app sensitivity", "Audit log schema: who, what, when, ticket_id, groups", "Design BigQuery or Firestore fields (no fake data)", "Agent rule: no grant without approved access governance ticket ID"],
                ["study-notes/prod-iam-audit.md"]),
            "thu": _day("agent", "Agent", "Okta MCP read vs write boundary.",
                ["Run projects/02-okta-mcp-server — list user groups (read-only)", "Define tool schema for agent: get_user, list_groups — NOT add_to_group", "Write path stays access governance API or human-approved workflow automation webhook"],
                ["projects/02-okta-mcp-server/"]),
            "fri": _day("measure", "Measure", "Grant turnaround time.",
                ["Baseline: request → provisioned duration (5 samples)", "Track approval step separately", "Target metric: approval_latency P50"],
                []),
            "sat": _day("prove", "Prove", "Access workflow doc for portfolio.",
                ["Write study-notes/week-05-access-workflow.md", "Include audit field schema", "Link to projects/06-cipher as future extension"],
                ["projects/06-cipher/"], "projects/06-cipher/"),
            "sun": _day("prove", "Prove", "CIPHER ship plan Phase 1 review.",
                ["Complete Phase 1 checklist in projects/06-cipher/SHIP-PLAN.md", "Architecture diagram for ABAC mover dry-run", "Honest status: architected, not shipped"],
                ["projects/06-cipher/SHIP-PLAN.md"], "projects/06-cipher/"),
        },
    },
    {
        "title": "CIPHER design — ABAC mover dry-run plan",
        "days": {
            "mon": _day("friction", "Friction", "Joiner/mover/leavers without CIPHER today.",
                ["How are functionalTeam group changes done manually?", "Jira Role Base / conversion ticket volume", "Error stories: wrong group, delayed mover"],
                ["projects/06-cipher/"]),
            "tue": _day("workflow", "Workflow", "CIPHER target flow: Jira → dry-run → Slack approve → apply.",
                ["Read SHIP-PLAN architecture diagram", "Define dry-run output format for stakeholders", "HITL: Slack approve before Okta apply"],
                ["projects/06-cipher/SHIP-PLAN.md"]),
            "wed": _day("identity", "Identity", "CIPHER service account + WIF.",
                ["Least-privilege SA for Cloud Run CIPHER", "WIF pattern — study-notes/wif-agent-identity-design.md", "No long-lived Okta SSWS in agent code"],
                ["study-notes/wif-agent-identity-design.md"]),
            "thu": _day("agent", "Agent", "CIPHER is NOT an LLM agent — deterministic automation.",
                ["Document why mover automation stays deterministic", "Agent role: only triage which Jira tickets trigger CIPHER", "Separate concerns: CIPHER vs helpdesk RAG agent"],
                ["projects/06-cipher/", "projects/01-it-helpdesk-agent/"]),
            "fri": _day("measure", "Measure", "Mover ticket handling time today.",
                ["Sample 3 mover tickets — manual steps and duration", "Metric target: delta computation time vs apply time"],
                []),
            "sat": _day("prove", "Prove", "CIPHER Phase 1 design doc section.",
                ["Draft cipher-architecture.md section in study-notes/", "Threat table from SHIP-PLAN", "Review with self — ready for stakeholder review?"],
                ["projects/06-cipher/"], "projects/06-cipher/"),
            "sun": _day("prove", "Prove", "Link CIPHER to portfolio README.",
                ["Ensure projects/06-cipher/README.md reflects accurate status", "Interview pitch paragraph (30 sec)"],
                ["projects/06-cipher/README.md"], "projects/06-cipher/"),
        },
    },
    {
        "title": "Audit trail + identity for agentic access workflow",
        "days": {
            "mon": _day("friction", "Friction", "Audit gaps in manual access changes.",
                ["Where are Okta System Log exports today?", "Can you trace a group change to a ticket?", "List gaps for compliance questions"],
                ["Okta System Log"]),
            "tue": _day("workflow", "Workflow", "Audit-first workflow design.",
                ["Every provision action writes: actor, target, groups, ticket_id, timestamp", "Failure path: log + Slack alert, no silent fail", "Idempotency key on access governance webhook handlers"],
                ["workflow automation error handling patterns"]),
            "wed": _day("identity", "Identity", "SCIM vs API grant patterns.",
                ["Which apps use SCIM push vs manual?", "access governance integration points", "Document for interview: identity-backed automation"],
                []),
            "thu": _day("agent", "Agent", "Agent audit: log every tool call.",
                ["Design log schema for agent tool invocations", "Include: prompt hash, tools_called, human_approval_id", "projects/02-okta-mcp-server — ensure read-only enforced"],
                ["projects/02-okta-mcp-server/server.py"]),
            "fri": _day("measure", "Measure", "Audit completeness check.",
                ["Pick 3 recent grants — can you reconstruct full chain?", "Score: complete / partial / missing"],
                []),
            "sat": _day("prove", "Prove", "Audit schema doc.",
                ["study-notes/week-07-audit-schema.md", "JSON example (fake user IDs OK)"],
                []),
            "sun": _day("prove", "Prove", "Month 2 capstone prep.",
                ["Checklist against months.json Month 2 rubric", "Gap list for Week 8"],
                ["tracker/months.json"]),
        },
    },
    {"title": "Month 2 capstone — identity audit trail + CIPHER link", "capstone": True},
]

# Weeks 9–36: extend with real content (abbreviated structure for remaining weeks)
# Fill weeks 9-36 programmatically with unit-specific real tasks


def _weeks_9_36() -> list[dict]:
    plans: list[dict] = []

    # Unit 3 — Agentic triage POC (9-12)
    unit3 = [
        ("Integrate helpdesk agent + Okta MCP narrative", "mon", "Agent", "Build case study outline: triage → read identity → escalate to access governance",
         ["Draft 1-page architecture for portfolio README", "Separate ADK agent from Okta MCP server repos", "HITL before any write"],
         ["projects/01-it-helpdesk-agent/", "projects/02-okta-mcp-server/"]),
        ("Eval: 10 triage prompts", "tue", "Agent", "Write 10 eval prompts (5 easy IT FAQ, 3 ambiguous, 2 must-escalate)",
         ["Run against helpdesk agent", "Log pass/fail — no fake accuracy %", "Save study-notes/week-09-evals.md"],
         ["projects/01-it-helpdesk-agent/"]),
        ("HITL approval gate design", "wed", "Workflow", "Design Slack approval before workflow automation/access governance action",
         ["Reuse Slack app modal patterns from governance app", "Timeout + fallback to human queue", "Document in case study"],
         ["Shipped Slack intake workflow"]),
        ("Failure + retry for agent path", "thu", "Workflow", "When agent confidence low → route to IT queue with context",
         ["Define confidence signals (not production ML — rules OK)", "Jira comment with agent reasoning", "No auto-close"],
         []),
        ("Case study draft v1", "sat", "Prove", "Write projects case study section in study-notes/agentic-case-study.md",
         ["Problem, architecture, HITL, honest POC status", "Link both portfolio projects"],
         ["projects/01-it-helpdesk-agent/"], "projects/01-it-helpdesk-agent/"),
        ("Okta MCP demo script", "sun", "Prove", "Record or script 2-min demo: NL query → Okta read",
         ["list user groups, check suspended status", "Portfolio interview walkthrough"],
         ["projects/02-okta-mcp-server/"], "projects/02-okta-mcp-server/"),
    ]
    for i, (title, _, *_) in enumerate(unit3):
        pass  # placeholder - build properly below

    # Simpler approach: dict mapping week number to plan
    extra: dict[int, dict] = {
        9: {
            "title": "Agentic case study — architecture draft",
            "days": {
                "mon": _day("friction", "Friction", "Ticket triage queue pain.",
                    ["Sample 10 service desk ticket titles — classify manually", "Note mis-routed tickets", "Agent opportunity: routing + KB"],
                    ["IT service desk"]),
                "tue": _day("workflow", "Workflow", "Case study flow: Slack/Jira intake → agent triage → HITL → access governance.",
                    ["Draw end-to-end diagram", "Mark deterministic vs agent steps", "Reference shipped Slack app"],
                    ["study-notes/agentic-case-study.md (create)"]),
                "wed": _day("identity", "Identity", "Read-only agent identity.",
                    ["Okta MCP scoped to read API only", "No SSWS in agent runtime", "WIF for Cloud Run if hosting agent"],
                    ["projects/02-okta-mcp-server/", "study-notes/wif-agent-identity-design.md"]),
                "thu": _day("agent", "Agent", "Run helpdesk agent + document gaps.",
                    ["5 test queries from Week 1", "Extend runbook corpus if needed", "Log in study-notes/week-09-agent-log.md"],
                    ["projects/01-it-helpdesk-agent/"]),
                "fri": _day("measure", "Measure", "Triage accuracy plan (not fake metrics).",
                    ["Define 10 eval cases", "Pass = correct route or correct KB answer", "Run weekly, track in spreadsheet"],
                    []),
                "sat": _day("prove", "Prove", "Case study draft section 1: Problem + Architecture.",
                    ["Write study-notes/agentic-case-study.md §1-2", "Honest POC label"],
                    ["study-notes/agentic-case-study.md"], "projects/01-it-helpdesk-agent/"),
                "sun": _day("prove", "Prove", "Polish README portfolio table entry.",
                    ["Update root README if case study path changed", "Cross-link projects 01+02"],
                    ["README.md"], "projects/01-it-helpdesk-agent/"),
            },
        },
        10: {
            "title": "Okta MCP + agent tool boundary",
            "days": {
                "mon": _day("friction", "Friction", "Identity lookup requests in tickets.",
                    ["How often do tickets need 'what groups is user X in?'", "Manual Okta admin steps today", "Agent saves: read via MCP"],
                    []),
                "tue": _day("workflow", "Workflow", "Tool-call flow in agent loop.",
                    ["User question → agent → okta_tool → formatted answer", "Never chain to write API", "Log tool calls"],
                    ["projects/01-it-helpdesk-agent/tools/okta_tool.py"]),
                "wed": _day("identity", "Identity", "MCP server scopes.",
                    ["Review projects/02-okta-mcp-server/server.py", "Document allowed Okta endpoints", "Rate limit / audit considerations"],
                    ["projects/02-okta-mcp-server/"]),
                "thu": _day("agent", "Agent", "10 eval cases for identity questions.",
                    ["Run MCP server locally", "Test: list groups, user status, app assignments (read-only)", "Log results"],
                    ["projects/02-okta-mcp-server/"]),
                "fri": _day("measure", "Measure", "Time saved estimate methodology.",
                    ["Manual Okta lookup: ~X min (your sample)", "Agent path: ~Y min", "Document method, not marketing %"],
                    []),
                "sat": _day("prove", "Prove", "Extend okta_tool or document integration gap.",
                    ["Note what you'd add for production", "Commit notes to study-notes/"],
                    ["projects/02-okta-mcp-server/"], "projects/02-okta-mcp-server/"),
                "sun": _day("prove", "Prove", "Case study §3: Identity layer.",
                    ["study-notes/agentic-case-study.md", "MCP diagram"],
                    [], "projects/02-okta-mcp-server/"),
            },
        },
        11: {
            "title": "HITL + Agentspace adoption patterns",
            "days": {
                "mon": _day("friction", "Friction", "Trust barriers to agent-assisted IT.",
                    ["Read projects/03-agentspace-rollout/README.md", "Note adoption friction from rollout doc", "Apply to internal IT agent"],
                    ["projects/03-agentspace-rollout/"]),
                "tue": _day("workflow", "Workflow", "HITL Slack approval prototype (paper or stub).",
                    ["Approver sees: ticket, agent recommendation, Okta action preview", "Approve/Reject buttons", "Rejected → back to queue"],
                    ["Shipped Slack app patterns"]),
                "wed": _day("identity", "Identity", "Approver authorization.",
                    ["Only app owner or manager can approve grants", "Map to Okta group or Slack user ID", "Audit approver identity"],
                    []),
                "thu": _day("agent", "Agent", "Prompt playbooks for IT ops.",
                    ["Read projects/04-prompt-playbooks/teams/it-ops.md", "Adapt 3 prompts for your triage agent", "Non-technical user language"],
                    ["projects/04-prompt-playbooks/"]),
                "fri": _day("measure", "Measure", "Adoption metrics plan.",
                    ["Align with projects/05-adoption-dashboard/README.md", "What would you log: queries, escalations, approvals"],
                    ["projects/05-adoption-dashboard/"]),
                "sat": _day("prove", "Prove", "HITL sequence diagram.",
                    ["Add to case study", "Mermaid in study-notes/"],
                    [], "projects/01-it-helpdesk-agent/"),
                "sun": _day("prove", "Prove", "Case study §4: HITL + failure modes.",
                    ["Retry, escalate, low-confidence paths", "No production claims"],
                    ["study-notes/agentic-case-study.md"], "projects/01-it-helpdesk-agent/"),
            },
        },
        12: {"title": "Month 3 capstone — agentic case study ship", "capstone": True},
        13: {
            "title": "Reliability — workflow automation + Cloud Run patterns from endpoint control service",
            "days": {
                "mon": _day("friction", "Friction", "Workflow failures you've seen.",
                    ["workflow automation execution failures — top 3 causes", "Manual reruns required?", "Document real incidents (sanitized)"],
                    ["workflow automation production"]),
                "tue": _day("workflow", "Workflow", "Idempotency keys on webhooks.",
                    ["Design idempotency for access governance/Okta callbacks", "Duplicate webhook handling", "Reference endpoint control service retry patterns"],
                    ["endpoint control service (shipped)"]),
                "wed": _day("identity", "Identity", "Credential rotation without downtime.",
                    ["Okta token rotation procedure", "WIF > long-lived keys", "Agent SA rotation plan"],
                    ["study-notes/wif-agent-identity-design.md"]),
                "thu": _day("agent", "Agent", "Agent timeout + fallback.",
                    ["Max tool-call iterations", "Fallback message to user", "Alert IT on repeated failures"],
                    []),
                "fri": _day("measure", "Measure", "Retry rate baseline.",
                    ["workflow automation failed executions / total (real ratio)", "Target: reduce with idempotency"],
                    []),
                "sat": _day("prove", "Prove", "Runbook stub for one workflow.",
                    ["study-notes/runbooks/access-grant-failure.md", "On-call steps"],
                    [], "projects/07-alius/"),
                "sun": _day("prove", "Prove", "Read ALIUS architecture for retry/DLQ patterns.",
                    ["projects/07-alius/ARCHITECTURE.md", "Compare to your access workflow"],
                    ["projects/07-alius/"], "projects/07-alius/"),
            },
        },
        14: {
            "title": "ALIUS offboarding design connection",
            "days": {
                "mon": _day("friction", "Friction", "Offboarding manual steps.",
                    ["List systems touched on deactivate", "Orphan NHIs you've seen?", "Link to ALIUS problem statement"],
                    ["projects/07-alius/ARCHITECTURE.md"]),
                "tue": _day("workflow", "Workflow", "ALIUS state machine sketch.",
                    ["Okta deactivate → Firestore steps", "Google sequence, Okta cleanup, device lookup", "Planning only — not shipped"],
                    ["projects/07-alius/"]),
                "wed": _day("identity", "Identity", "NHI revoke on offboard.",
                    ["Service accounts tied to humans", "KeySentinel / revoke sequence in ALIUS doc", "Interview SD: offboarding-pipeline.md"],
                    ["interview-prep/answers/offboarding-pipeline.md"]),
                "thu": _day("agent", "Agent", "Agent credentials on offboard.",
                    ["If user had agent API keys — revoke in workflow", "Future: agent identity broker design"],
                    ["interview-prep/answers/agent-identity-broker.md"]),
                "fri": _day("measure", "Measure", "Offboard completion tracking.",
                    ["Metric: % terminal states in state machine (when ALIUS exists)", "Today: manual checklist completion"],
                    []),
                "sat": _day("prove", "Prove", "ALIUS design questions checklist.",
                    ["Complete Week 7 questions in ARCHITECTURE.md", "2-min pitch written"],
                    ["projects/07-alius/ARCHITECTURE.md"], "projects/07-alius/"),
                "sun": _day("prove", "Prove", "Link ALIUS + access workflow in platform-bridge.",
                    ["study-notes/platform-projects/platform-bridge.md", "Update if needed"],
                    ["study-notes/platform-projects/platform-bridge.md"], "projects/07-alius/"),
            },
        },
        15: {
            "title": "Alerting + Slack ops notifications",
            "days": {
                "mon": _day("friction", "Friction", "Silent workflow failures.",
                    ["When did automation fail without alert?", "Gap list"],
                    []),
                "tue": _day("workflow", "Workflow", "Slack alert on workflow automation/Cloud Run failure.",
                    ["Webhook to #it-automation-alerts", "Include execution ID, workflow name, error", "Reuse Slack app bot token patterns"],
                    ["Slack app (shipped)"]),
                "wed": _day("identity", "Identity", "Alert channel access.",
                    ["Who can see automation alerts?", "Least privilege on webhook URLs"],
                    []),
                "thu": _day("agent", "Agent", "Agent failure alerts.",
                    ["Separate alert when agent escalates 3x same issue", "Not spam on every low-confidence"],
                    []),
                "fri": _day("measure", "Measure", "MTTR for automation failures.",
                    ["Time from fail → human fix (sample)", "Target reduction with runbooks"],
                    []),
                "sat": _day("prove", "Prove", "Alert payload JSON example.",
                    ["study-notes/week-15-alerts.md"],
                    []),
                "sun": _day("prove", "Prove", "Month 4 capstone prep.",
                    ["Reliability checklist draft", "months.json Month 4 rubric"],
                    ["tracker/months.json"]),
            },
        },
        16: {"title": "Month 4 capstone — reliability runbook", "capstone": True},
        17: {
            "title": "Agent tool schemas — helpdesk + Okta tools",
            "days": {
                "mon": _day("friction", "Friction", "Tool misuse risks.",
                    ["Agent calls wrong tool or args", "Document 3 failure modes"],
                    []),
                "tue": _day("workflow", "Workflow", "JSON schema for each tool.",
                    ["rag_tool, okta_tool in helpdesk agent", "Required fields, enums", "Validate before Okta API call"],
                    ["projects/01-it-helpdesk-agent/tools/"]),
                "wed": _day("identity", "Identity", "Tool scope tied to requester.",
                    ["Agent can only lookup users relevant to ticket", "No arbitrary user enumeration in prod"],
                    []),
                "thu": _day("agent", "Agent", "Expand eval set to 20 cases.",
                    ["Add edge cases: empty query, ambiguous user", "Log in study-notes/week-17-evals.md"],
                    ["projects/01-it-helpdesk-agent/"]),
                "fri": _day("measure", "Measure", "Tool call error rate.",
                    ["Track schema validation failures in test runs"],
                    []),
                "sat": _day("prove", "Prove", "Eval results table.",
                    ["study-notes/week-17-evals.md", "No fake accuracy — raw pass/fail"],
                    []),
                "sun": _day("prove", "Prove", "Guardrails doc.",
                    ["Max tools per turn, block list for destructive ops"],
                    []),
            },
        },
        18: {
            "title": "Eval harness structure",
            "days": {
                "mon": _day("friction", "Friction", "Regression when changing prompts.",
                    ["Note prompt change that broke answers", "Why evals matter"],
                    []),
                "tue": _day("workflow", "Workflow", "Eval runner script outline.",
                    ["Input: CSV of prompt, expected_route, expected_contains", "Output: pass/fail log", "Run in CI optional"],
                    ["projects/01-it-helpdesk-agent/"]),
                "wed": _day("identity", "Identity", "Eval data — no real employee PII.",
                    ["Synthetic users in test tenant", "Sanitized ticket titles"],
                    []),
                "thu": _day("agent", "Agent", "Implement or stub 5 eval runs.",
                    ["Python script or notebook", "Commit to study-notes/evals/"],
                    []),
                "fri": _day("measure", "Measure", "Eval pass rate tracking.",
                    ["Track over time in spreadsheet — real runs only"],
                    []),
                "sat": _day("prove", "Prove", "eval_cases.csv with 10 rows.",
                    ["study-notes/evals/eval_cases.csv"],
                    []),
                "sun": _day("prove", "Prove", "Document when agent must escalate.",
                    ["Add to case study §5"],
                    ["study-notes/agentic-case-study.md"]),
            },
        },
        19: {
            "title": "Guardrails + escalation policy",
            "days": {
                "mon": _day("friction", "Friction", "High-risk requests agents must never auto-handle.",
                    ["Admin grants, bulk deletes, production changes"],
                    []),
                "tue": _day("workflow", "Workflow", "Escalation policy doc.",
                    ["Tier 1: agent auto | Tier 2: agent + HITL | Tier 3: human only", "Map your ticket categories"],
                    []),
                "wed": _day("identity", "Identity", "Privileged access workflow.",
                    ["Separate path from standard access governance request", "No agent write to privileged groups"],
                    []),
                "thu": _day("agent", "Agent", "System prompt guardrails.",
                    ["Draft system prompt section: never claim authority to grant access", "Cite KB sources when answering"],
                    []),
                "fri": _day("measure", "Measure", "Escalation rate tracking.",
                    ["Count escalations / total agent sessions in tests"],
                    []),
                "sat": _day("prove", "Prove", "escalation-policy.md",
                    ["study-notes/escalation-policy.md"],
                    []),
                "sun": _day("prove", "Prove", "Month 5 capstone prep.",
                    ["Eval harness + guardrails checklist"],
                    ["tracker/months.json"]),
            },
        },
        20: {"title": "Month 5 capstone — eval harness", "capstone": True},
        21: {
            "title": "Ops KB structure for RAG",
            "days": {
                "mon": _day("friction", "Friction", "KB gaps from agent test failures.",
                    ["List runbook topics agent couldn't answer", "Prioritize top 5 to author"],
                    []),
                "tue": _day("workflow", "Workflow", "Runbook markdown structure.",
                    ["Title, symptoms, steps, escalation", "Match projects/01-it-helpdesk-agent runbook format"],
                    ["projects/01-it-helpdesk-agent/"]),
                "wed": _day("identity", "Identity", "KB access control.",
                    ["Which runbooks contain sensitive info?", "Segment internal-only vs general IT"],
                    []),
                "thu": _day("agent", "Agent", "Grounding rules.",
                    ["Agent must cite runbook section", "If no KB hit → say so, don't hallucinate"],
                    []),
                "fri": _day("measure", "Measure", "KB coverage metric.",
                    ["% of eval cases with matching runbook chunk (from tests)"],
                    []),
                "sat": _day("prove", "Prove", "Author 2 new runbook snippets.",
                    ["Add to helpdesk agent corpus", "Re-run 3 failing evals"],
                    ["projects/01-it-helpdesk-agent/"]),
                "sun": _day("prove", "Prove", "KB index doc.",
                    ["study-notes/ops-kb-index.md"],
                    []),
            },
        },
        22: {
            "title": "RAG tuning — when not to use RAG",
            "days": {
                "mon": _day("friction", "Friction", "Wrong RAG answers.",
                    ["Examples of retrieval mismatch", "When keyword search fails"],
                    []),
                "tue": _day("workflow", "Workflow", "Hybrid: RAG for FAQ, deterministic for status.",
                    ["User status → Okta MCP not RAG", "Policy questions → RAG"],
                    []),
                "wed": _day("identity", "Identity", "Don't embed secrets in KB.",
                    ["Audit runbooks for tokens, internal URLs", "Redact if needed"],
                    []),
                "thu": _day("agent", "Agent", "Chunk size / metadata experiments.",
                    ["Note 2 chunk strategies tested", "Which worked for IT runbooks"],
                    ["projects/01-it-helpdesk-agent/tools/rag_tool.py"]),
                "fri": _day("measure", "Measure", "Retrieval precision (manual review).",
                    ["For 10 queries: relevant chunk retrieved yes/no"],
                    []),
                "sat": _day("prove", "Prove", "Update case study KB section.",
                    ["study-notes/agentic-case-study.md"],
                    []),
                "sun": _day("prove", "Prove", "Fallback flow diagram.",
                    ["No KB match → escalate with collected context"],
                    []),
            },
        },
        23: {
            "title": "Wire KB into triage flow",
            "days": {
                "mon": _day("friction", "Friction", "Stale runbooks.",
                    ["Last updated dates on key docs", "Ownership for KB maintenance"],
                    []),
                "tue": _day("workflow", "Workflow", "KB update process.",
                    ["Ticket resolves with new fix → runbook PR", "Owner: IT ops"],
                    []),
                "wed": _day("identity", "Identity", "KB repo access.",
                    ["Who can merge runbook changes?", "Same as internal docs policy"],
                    []),
                "thu": _day("agent", "Agent", "End-to-end demo path.",
                    ["Query → RAG → answer OR → MCP lookup OR → escalate", "Script demo for portfolio"],
                    ["projects/01-it-helpdesk-agent/"]),
                "fri": _day("measure", "Measure", "Self-service resolution in tests.",
                    ["Count eval passes without escalation"],
                    []),
                "sat": _day("prove", "Prove", "Record demo script.",
                    ["study-notes/demo-script.md", "2-min portfolio walkthrough"],
                    []),
                "sun": _day("prove", "Prove", "Month 6 capstone prep.",
                    ["KB + case study complete checklist"],
                    ["tracker/months.json"]),
            },
        },
        24: {"title": "Month 6 capstone — KB integrated case study", "capstone": True},
        25: {
            "title": "Metrics baseline + adoption dashboard",
            "days": {
                "mon": _day("friction", "Friction", "No visibility into automation value.",
                    ["What can't you measure today?", "Gap list for leadership story"],
                    []),
                "tue": _day("workflow", "Workflow", "Adoption dashboard data model.",
                    ["Read projects/05-adoption-dashboard/README.md", "Events: query, approval, grant, failure", "BigQuery or Logging sink"],
                    ["projects/05-adoption-dashboard/"]),
                "wed": _day("identity", "Identity", "PII in metrics.",
                    ["Hash user IDs in logs", "Aggregate only for dashboards"],
                    []),
                "thu": _day("agent", "Agent", "Log agent sessions for dashboard.",
                    ["Schema: timestamp, tools, outcome, duration"],
                    ["projects/05-adoption-dashboard/"]),
                "fri": _day("measure", "Measure", "Hours saved calculation.",
                    ["Formula: (manual_min - automated_min) * volume", "Document assumptions — real volume only"],
                    []),
                "sat": _day("prove", "Prove", "Metrics one-pager.",
                    ["study-notes/metrics-baseline.md", "3 metrics you can collect this quarter"],
                    ["projects/05-adoption-dashboard/"], "projects/05-adoption-dashboard/"),
                "sun": _day("prove", "Prove", "Consulting offer (a) outline.",
                    ["Okta JML audit — scope from CONTEXT.md", "Fixed-fee structure draft"],
                    ["CONTEXT.md"], "projects/05-adoption-dashboard/"),
            },
        },
        26: {
            "title": "Consulting packaging (a)(b)(c)",
            "days": {
                "mon": _day("friction", "Friction", "Consulting buyer pain.",
                    ["Who buys Okta audits? IT lead, security, fast-growing startup IT"],
                    []),
                "tue": _day("workflow", "Workflow", "Offer (b) access automation deck.",
                    ["Intake → access governance/Okta — your production experience", "Deliverables list"],
                    ["CONTEXT.md consulting (b)"]),
                "wed": _day("identity", "Identity", "Offer (c) AI triage bot POC.",
                    ["Scope: Slack + agent + HITL — portfolio case study", "4-6 week POC, fixed fee"],
                    ["CONTEXT.md consulting (c)"]),
                "thu": _day("agent", "Agent", "Demo reel outline.",
                    ["helpdesk agent + MCP + HITL slide sequence"],
                    ["study-notes/demo-script.md"]),
                "fri": _day("measure", "Measure", "LinkedIn post draft metrics.",
                    ["Shipped X at production IT — no invented %", "Portfolio links"],
                    []),
                "sat": _day("prove", "Prove", "consulting-one-pager.md",
                    ["study-notes/consulting-one-pager.md", "Offers (a)(b)(c)"],
                    []),
                "sun": _day("prove", "Prove", "Update wave-1-checklist.",
                    ["interview-prep/answers/wave-1-checklist.md"],
                    ["interview-prep/answers/wave-1-checklist.md"]),
            },
        },
        27: {
            "title": "Portfolio narrative single story",
            "days": {
                "mon": _day("friction", "Friction", "Interview gap: scattered projects.",
                    ["List what feels disconnected", "Unify under identity-backed ops automation"],
                    []),
                "tue": _day("workflow", "Workflow", "platform-bridge walkthrough.",
                    ["study-notes/platform-projects/platform-bridge.md", "5-min talk track rehearse"],
                    ["study-notes/platform-projects/platform-bridge.md"]),
                "wed": _day("identity", "Identity", "STAR: Okta/access governance shipped work.",
                    ["interview-prep/answers/behavioral-star.md — fill Slack/workflow automation/endpoint control service"],
                    ["interview-prep/answers/behavioral-star.md"]),
                "thu": _day("agent", "Agent", "STAR: agentic case study (POC honest).",
                    ["Fill behavioral-star agentic section"],
                    []),
                "fri": _day("measure", "Measure", "Portfolio completeness checklist.",
                    ["All 7 projects linked", "Status labels accurate"],
                    ["README.md"]),
                "sat": _day("prove", "Prove", "Record yourself — 5 min portfolio narrated.",
                    ["Notes on weak sections to fix"],
                    []),
                "sun": _day("prove", "Prove", "Month 7 capstone prep.",
                    ["Consulting + metrics rubric"],
                    ["tracker/months.json"]),
            },
        },
        28: {"title": "Month 7 capstone — consulting one-pager + metrics", "capstone": True},
    }

    # Interview weeks 29-36
    for w in range(29, 33):
        extra[w] = {
            "title": f"Interview prep — AI Systems system design (Week {w})",
            "days": {
                "mon": _day("friction", "Friction", "Target company research.",
                    [f"Research 1 company for Wave 1 (week {w})", "Note their ops/automation stack", "Write 3 interview questions you'd ask them"],
                    ["CONTEXT.md target companies"]),
                "tue": _day("workflow", "Workflow", "Timed system design (45 min).",
                    ["Prompt: design AI-native internal IT ticket automation", "Use interview-prep/system-design-template.md", "Submit written answer"],
                    ["interview-prep/system-design-template.md"]),
                "wed": _day("identity", "Identity", "Timed design: Okta + agent identity.",
                    ["Prompt: agent identity broker or access grant automation", "Include HITL + audit"],
                    ["interview-prep/answers/agent-identity-broker.md"]),
                "thu": _day("agent", "Agent", "Portfolio walkthrough rehearsal.",
                    ["10-min: shipped work → case study → CIPHER/ALIUS design", "Record or script"],
                    ["study-notes/demo-script.md"]),
                "fri": _day("measure", "Interview prep", f"Week {w} mock block.",
                    ["1 system design review (self-grade rubric)", "1 STAR aloud", "1 company research summary"],
                    ["interview-prep/answers/wave-1-checklist.md"]),
                "sat": _day("prove", "Prove", "Save design answer to interview-prep/answers/.",
                    ["File: week-{w}-system-design.md"],
                    ["interview-prep/answers/"]),
                "sun": _day("prove", "Prove", "Update resume bullet from this week's STAR.",
                    ["Kamaal_Mirza_Resume_Serval.docx — align wording"],
                    []),
            },
        }

    for w in range(33, 36):
        extra[w] = {
            "title": f"Apply + iterate — Wave 1 (Week {w})",
            "days": {
                "mon": _day("friction", "Friction", "Application pipeline.",
                    ["Update apply tracker: company, role, date, status", "3 target companies minimum"],
                    ["interview-prep/answers/wave-1-checklist.md"]),
                "tue": _day("workflow", "Workflow", "Tailor resume per role.",
                    ["Highlight shipped + portfolio demo + case study", "No AI Security lead framing"],
                    []),
                "wed": _day("identity", "Identity", "LinkedIn + GitHub pins.",
                    ["Pin ai-systems-portfolio", "About section: AI Systems positioning"],
                    ["README.md"]),
                "thu": _day("agent", "Agent", "Refine case study from feedback.",
                    ["If any mock feedback — update agentic-case-study.md", "Honest POC status always"],
                    ["study-notes/agentic-case-study.md"]),
                "fri": _day("measure", "Interview prep", "Follow-up + networking.",
                    ["1 LinkedIn outreach to AI ops engineer at target co", "1 recruiter reply if applicable"],
                    []),
                "sat": _day("prove", "Prove", "Submit 1 application or referral ask.",
                    ["Log in apply tracker"],
                    []),
                "sun": _day("prove", "Prove", "Retro: what's working in outreach.",
                    ["study-notes/apply-retro.md"],
                    []),
            },
        }
    extra[36] = {"title": "Program capstone — portfolio + apply tracker", "capstone": True}

    return extra


def get_week_plan(week: int) -> dict | None:
    if week <= len(WEEK_PLANS):
        p = WEEK_PLANS[week - 1]
        if p.get("capstone"):
            return None
        return p
    extra = _weeks_9_36()
    if week in extra:
        p = extra[week]
        if p.get("capstone"):
            return None
        return p
    return None
