"""36-week curriculum: weekly theme → mini-project → flagship capstone."""

from __future__ import annotations

# competency: harness | identity | endpoint | enablement | workflow | ops | platform | portfolio

MINI_PROJECTS: list[dict] = [
    # ── Phase 1: Agent foundation (W1–4) ──
    {
        "title": "Ops friction → agent scope",
        "theme": "Ops friction → agent scope",
        "learn": "High-volume IT friction; when agent helps vs deterministic automation",
        "competency": "harness",
        "path": "projects/01-it-helpdesk-agent/",
        "feeds": ["M1"],
        "build": [
            "Set up Python venv; install requirements.txt",
            "Add 2 Markdown runbooks (VPN, SSO, or MDM)",
            "Run 5 test queries; log results in prove log",
        ],
        "doneWhen": [
            "Agent starts (or document blocker + workaround)",
            "2 runbooks committed",
            "study-notes/weeks/week-01-prove-log.md filled",
        ],
    },
    {
        "title": "Identity tools for agents (Okta MCP)",
        "theme": "Identity tools for agents",
        "learn": "MCP tool design; read-only Okta scopes; least-privilege tokens",
        "competency": "identity",
        "path": "projects/02-okta-mcp-server/",
        "feeds": ["M2"],
        "build": [
            "Configure read-only Okta API token (preview/sandbox org)",
            "Verify list_users + get_group_members tools",
            "Document 3 sample queries (redact PII)",
        ],
        "doneWhen": ["MCP server runs", "3 queries logged in project README or notes"],
    },
    {
        "title": "Agent ↔ Okta MCP wiring",
        "theme": "Agent ↔ identity wiring",
        "learn": "Tool schemas; write escalation; agent never writes Okta directly",
        "competency": "harness",
        "path": "projects/01-it-helpdesk-agent/",
        "feeds": ["M1", "M2"],
        "build": [
            "Wire agent to Okta MCP tools",
            "System prompt: identity lookups read-only; escalate writes",
            "Test group membership + user status queries",
        ],
        "doneWhen": ["2+ identity query types work", "Write attempt triggers escalation"],
    },
    {
        "title": "Guardrails as product",
        "theme": "Guardrails as product",
        "learn": "Escalation policy as a shippable artifact, not a prompt footnote",
        "competency": "harness",
        "path": "projects/01-it-helpdesk-agent/",
        "feeds": ["M1"],
        "build": [
            "Write docs/escalation-policy.md",
            "3 must-escalate + 3 safe-to-answer examples",
            "Update agent system prompt to cite policy",
        ],
        "doneWhen": ["escalation-policy.md committed", "6 examples tested and logged"],
    },
    # ── Phase 2: Okta IaC + agent identity (W5–8) ──
    {
        "title": "Okta topology as code — groups",
        "theme": "Okta topology as code",
        "learn": "Okta Terraform provider; groups + group rules as access topology",
        "competency": "identity",
        "path": "projects/11-okta-iac/",
        "feeds": ["M8"],
        "build": [
            "Scaffold providers.tf + modules/groups for sandbox Okta org",
            "Define app-access + role groups (e.g. agent-read-identity, role-it-approvers)",
            "Write docs/ACCESS-TOPOLOGY.md diagram",
        ],
        "doneWhen": [
            "terraform plan succeeds against sandbox",
            "Groups module applied (or plan committed with apply notes)",
            "ACCESS-TOPOLOGY.md committed",
        ],
    },
    {
        "title": "Okta apps + policies as code",
        "theme": "Apps + policies as code",
        "learn": "App integrations, group assignments, sign-on/MFA policies in Terraform",
        "competency": "identity",
        "path": "projects/11-okta-iac/",
        "feeds": ["M8"],
        "build": [
            "Add modules/apps (OIDC or SAML stub) + group assignments",
            "Add modules/policies for sign-on / MFA resources provider supports",
            "Document API-manageable vs console-only policy gaps",
        ],
        "doneWhen": [
            "Apps + policies modules present",
            "terraform plan shows expected resources",
            "Policy gap notes in README or docs/",
        ],
    },
    {
        "title": "Access automation boundary + sandbox users",
        "theme": "Access automation boundary",
        "learn": "TF owns topology; SCIM/agent owns user lifecycle; CIPHER design tie-in",
        "competency": "identity",
        "path": "projects/11-okta-iac/",
        "feeds": ["M8"],
        "build": [
            "Add modules/users_sandbox with tf-demo-* users only",
            "Write docs/AGENT-CONTRACT.md (groups MCP may read; writes need HITL)",
            "Update projects/06-cipher design: TF topology vs automation membership",
        ],
        "doneWhen": [
            "Sandbox users module + boundary documented in README",
            "AGENT-CONTRACT.md committed",
            "CIPHER sequence note updated (honest architected status)",
        ],
    },
    {
        "title": "GCP secrets + platform IaC skeleton",
        "theme": "Secrets + GCP IaC skeleton",
        "learn": "Secret Manager, SA roles, WIF concepts; never plaintext Okta tokens in git",
        "competency": "platform",
        "path": "projects/10-platform-foundation/",
        "feeds": ["M6"],
        "build": [
            "Scaffold Terraform: SA + Secret Manager placeholders for agent/Okta creds",
            "Document WIF / no-SA-keys pattern in README",
            "Link pattern for Okta API token → Secret Manager (sandbox)",
        ],
        "doneWhen": [
            "Terraform stub validates (terraform init/validate)",
            "Secrets pattern documented",
            "No credentials committed",
        ],
    },
    # ── Phase 3: Workflow + containers (W9–12) ──
    {
        "title": "HITL before side effects",
        "theme": "HITL before side effects",
        "learn": "Approval gate patterns; propose add-to-group against IaC-known groups",
        "competency": "workflow",
        "path": "projects/01-it-helpdesk-agent/",
        "feeds": ["M3"],
        "build": [
            "docs/hitl-flow.md with sequence diagram",
            "Mock approval: CLI y/n or Slack Block Kit draft",
            "Block side-effect (e.g. group add) without approval",
        ],
        "doneWhen": ["Demo: action blocked without approval", "Diagram committed"],
    },
    {
        "title": "Agent as a service (FastAPI)",
        "theme": "Agent as a service",
        "learn": "HTTP contracts with Pydantic; health + query API",
        "competency": "workflow",
        "path": "projects/01-it-helpdesk-agent/",
        "feeds": ["M3"],
        "build": [
            "FastAPI POST /query with Pydantic models",
            "Return answer + tools_used + escalated flag",
            "curl example in README",
        ],
        "doneWhen": ["/query works locally", "Health check endpoint"],
    },
    {
        "title": "Idempotent webhook handler",
        "theme": "Webhook reliability",
        "learn": "Idempotency-Key, retries, duplicate handling for intake",
        "competency": "workflow",
        "path": "projects/01-it-helpdesk-agent/",
        "feeds": ["M3"],
        "build": [
            "POST /hooks/ticket with Idempotency-Key header",
            "docs/reliability.md: retry + duplicate handling",
            "Test duplicate POST returns same response",
        ],
        "doneWhen": ["Reliability doc + test log"],
    },
    {
        "title": "Containerize the control plane",
        "theme": "Containerize the control plane",
        "learn": "Docker multi-stage builds; compose for agent + MCP",
        "competency": "platform",
        "path": "projects/01-it-helpdesk-agent/",
        "feeds": ["M1", "M6"],
        "build": [
            "Dockerfile (multi-stage) for agent API",
            "docker-compose.yml: agent + MCP (or documented stub)",
            "One-command local run documented in README",
        ],
        "doneWhen": ["compose up (or documented equivalent) works", "No secrets in image"],
    },
    # ── Phase 4: Evals, events, CI (W13–16) ──
    {
        "title": "Eval harness — 5 cases",
        "theme": "Eval harness (core)",
        "learn": "Golden cases for tool-use; honest pass/fail — no invented accuracy %",
        "competency": "ops",
        "path": "projects/01-it-helpdesk-agent/",
        "feeds": ["M4"],
        "build": [
            "evals/eval_cases.csv: query, expected_behavior, pass/fail",
            "5 rows: runbook + identity read",
            "evals/results.md with honest outcomes",
        ],
        "doneWhen": ["CSV + results committed", "No invented accuracy %"],
    },
    {
        "title": "Eval harness — adversarial 15",
        "theme": "Eval harness (adversarial)",
        "learn": "Privilege escalation, KB miss, ambiguous user cases",
        "competency": "ops",
        "path": "projects/01-it-helpdesk-agent/",
        "feeds": ["M4"],
        "build": [
            "Expand to 15 cases including escalation + KB miss",
            "Top 3 failures → fix plan before capstone",
        ],
        "doneWhen": ["15 rows in CSV", "Failure analysis in results.md"],
    },
    {
        "title": "Unified ops event stream",
        "theme": "Unified ops event stream",
        "learn": "One schema for query/tool/approve/fail; Pub/Sub or log pipeline stub",
        "competency": "ops",
        "path": "projects/05-adoption-dashboard/",
        "feeds": ["M5"],
        "build": [
            "events-schema.md: query_submitted, tool_called, escalated, approved",
            "Publisher stub (Pub/Sub or structured log) + sample events",
            "Dashboard script from sample logs only",
        ],
        "doneWhen": ["Schema + script run on test data", "Screenshot or terminal output saved"],
    },
    {
        "title": "CI for identity + agent",
        "theme": "CI for identity + agent",
        "learn": "GitHub Actions: terraform plan on Okta IaC + lint/test/build agent image",
        "competency": "platform",
        "path": "projects/11-okta-iac/",
        "feeds": ["M6", "M8"],
        "build": [
            "GitHub Actions workflow: terraform fmt/validate/plan for 11-okta-iac",
            "CI job: lint/test (or build) for agent/API project",
            "Document required secrets (OKTA_*, GCP) — never commit values",
        ],
        "doneWhen": ["CI workflow files committed", "Plan job documented as green or blocked with reason"],
    },
    # ── Phase 5: Endpoint + K8s literacy + assemble prep (W17–20) ──
    {
        "title": "Endpoint AI governance policy",
        "theme": "Endpoint AI governance",
        "learn": "MDM policy tiers; shadow AI; link identity groups → tool tiers",
        "competency": "endpoint",
        "path": "projects/09-endpoint-ai-governance/",
        "feeds": ["capstone"],
        "build": [
            "POLICY.md: approved vs prohibited AI tool categories",
            "MDM-ROLLOUT-CHECKLIST.md (generic, no employer URLs)",
            "Map Okta groups from 11-okta-iac to allowed tool tiers",
        ],
        "doneWhen": ["Both docs committed", "No internal employer data"],
    },
    {
        "title": "Offboarding orchestration (ALIUS)",
        "theme": "Offboarding orchestration",
        "learn": "Deterministic vs agent-assisted steps; revoke TF-managed app groups",
        "competency": "endpoint",
        "path": "projects/07-alius/",
        "feeds": ["capstone"],
        "build": [
            "Review ARCHITECTURE.md",
            "Diagram: device wipe + Okta deactivate + SaaS revoke order",
            "Note where agent assists vs deterministic; reference M8 groups",
        ],
        "doneWhen": ["Updated architecture section", "Honest planning status"],
    },
    {
        "title": "Cloud Run vs Kubernetes literacy",
        "theme": "Cloud Run vs Kubernetes",
        "learn": "K8s literacy (kind or GKE Autopilot touch) + when Cloud Run wins for agents",
        "competency": "platform",
        "path": "study-notes/cloud-platform/",
        "feeds": ["M6"],
        "build": [
            "Write study-notes/cloud-platform/run-vs-gke.md tradeoff memo",
            "Optional: kind or GKE Autopilot hello deploy notes",
            "Recommend default hosting for capstone agent (Cloud Run)",
        ],
        "doneWhen": ["Tradeoff memo committed", "Clear hosting recommendation for capstone"],
    },
    {
        "title": "Capstone architecture freeze",
        "theme": "Capstone architecture freeze",
        "learn": "Map M1–M8 into one control plane; freeze demo script",
        "competency": "harness",
        "path": "projects/08-capstone-ops-agent/",
        "feeds": ["capstone"],
        "build": [
            "ARCHITECTURE.md: M1–M8 mapped to components",
            "demo-script.md: Okta TF → runbook Q → identity Q → HITL → audit → metrics",
            "Repo layout scaffold (folders + README)",
        ],
        "doneWhen": ["Architecture + demo script committed", "Eval failures from W14 addressed in plan"],
    },
]

CAPSTONE_WEEKS = [
    {
        "title": "Capstone W1 — Assemble control plane",
        "theme": "Assemble control plane",
        "learn": "Integrate agent, MCP, HITL, evals; MCP reads TF-managed sandbox groups",
        "competency": "harness",
        "path": "projects/08-capstone-ops-agent/",
        "feeds": ["capstone"],
        "build": [
            "Merge agent + MCP + FastAPI into capstone layout",
            "One local run script or docker-compose",
            "Port eval suite; MCP queries TF-managed sandbox groups",
        ],
        "doneWhen": ["Single start command", "5 eval cases pass in capstone repo"],
    },
    {
        "title": "Capstone W2 — Identity + HITL enforcement",
        "theme": "Enforce identity + HITL",
        "learn": "Unapproved writes blocked; propose changes only against IaC-known groups",
        "competency": "identity",
        "path": "projects/08-capstone-ops-agent/",
        "feeds": ["capstone"],
        "build": [
            "HITL gate before side effects",
            "Audit log on every query",
            "Reject privilege escalation; only IaC-known groups in write proposals",
        ],
        "doneWhen": ["Unapproved writes blocked", "Audit samples logged"],
    },
    {
        "title": "Capstone W3 — Observability + policy",
        "theme": "Observability + policy",
        "learn": "Endpoint policy stub; OTel/metrics; SLO sketch; event plane",
        "competency": "ops",
        "path": "projects/08-capstone-ops-agent/",
        "feeds": ["M7", "capstone"],
        "build": [
            "Wire endpoint policy stub from projects/09",
            "Structured logs + OTel/metrics stub + short SLO note",
            "Adoption/event plane reads capstone logs",
        ],
        "doneWhen": ["Policy check in demo flow", "Metrics + SLO note present"],
    },
    {
        "title": "Capstone W4 — Deliver cloud + identity",
        "theme": "Deliver cloud + identity",
        "learn": "GCP Terraform + CI → Cloud Run; Okta TF plan in CI; honest case study",
        "competency": "platform",
        "path": "projects/08-capstone-ops-agent/",
        "feeds": ["M6", "M8", "capstone"],
        "build": [
            "Cloud Run deploy via projects/10-platform-foundation (or documented script)",
            "Confirm Okta IaC CI plan path still valid",
            "study-notes/capstone-case-study.md with honest limits",
        ],
        "doneWhen": ["Deploy instructions", "Case study committed", "Portfolio README updated"],
    },
]

PORTFOLIO_WEEKS = [
    {
        "title": "Capstone demo polish (2 min)",
        "theme": "Demo polish",
        "learn": "Hiring-manager demo: Okta IaC → agent → HITL → audit → Cloud Run",
        "competency": "portfolio",
        "path": "projects/08-capstone-ops-agent/",
        "feeds": ["capstone"],
        "build": ["Rehearse demo-script.md", "Fix top 3 eval failures", "README architecture diagram"],
        "doneWhen": ["Demo under 2 minutes", "README diagram"],
    },
    {
        "title": "Portfolio narrative",
        "theme": "Portfolio narrative",
        "learn": "One story: shipped work + M1–M8 + flagship control plane",
        "competency": "portfolio",
        "path": "study-notes/platform-projects/platform-bridge.md",
        "feeds": ["capstone"],
        "build": ["Update platform-bridge.md", "LinkedIn draft linking minis + capstone"],
        "doneWhen": ["Narrative links shipped work + M1–M8 + capstone"],
    },
    {
        "title": "Recruiter technical one-pager",
        "theme": "Recruiter one-pager",
        "learn": "Technical portfolio summary (not consulting-first)",
        "competency": "portfolio",
        "path": "study-notes/",
        "feeds": ["capstone"],
        "build": ["study-notes/recruiter-one-pager.md: flagship + 8 minis + stack"],
        "doneWhen": ["One-pager committed and linked from README"],
    },
    {
        "title": "Metrics honesty pass",
        "theme": "Metrics honesty pass",
        "learn": "Baseline formulas from real volume only",
        "competency": "ops",
        "path": "projects/05-adoption-dashboard/",
        "feeds": ["M5"],
        "build": ["study-notes/metrics-baseline.md from real volume only"],
        "doneWhen": ["Formula documented, no fake %"],
    },
    {
        "title": "System design #1 — Okta-as-code + SCIM",
        "theme": "System design: Okta-as-code",
        "learn": "TF topology vs SCIM lifecycle; agent HITL for membership",
        "competency": "portfolio",
        "path": "interview-prep/",
        "feeds": ["M8"],
        "build": ["45-min timed design → interview-prep/answers/okta-iac-scim-boundary.md"],
        "doneWhen": ["Written design committed"],
    },
    {
        "title": "System design #2 — agent identity + Cloud Run vs GKE",
        "theme": "System design: agent hosting",
        "learn": "WIF + MCP + HITL; Cloud Run vs GKE for agent workloads",
        "competency": "portfolio",
        "path": "interview-prep/",
        "feeds": ["M6"],
        "build": ["Timed design: WIF + MCP + HITL + hosting tradeoff"],
        "doneWhen": ["Design doc committed"],
    },
    {
        "title": "STAR stories + resume",
        "theme": "STAR + resume",
        "learn": "Bullets for Okta TF, MCP, HITL, GCP delivery, capstone",
        "competency": "portfolio",
        "path": "interview-prep/answers/behavioral-star.md",
        "feeds": ["capstone"],
        "build": ["STAR: automation, Okta IaC, capstone", "Resume bullets"],
        "doneWhen": ["behavioral-star.md updated"],
    },
    {
        "title": "Mock interview block",
        "theme": "Mock interview",
        "learn": "Design aloud + STAR + 2-min capstone demo",
        "competency": "portfolio",
        "path": "interview-prep/",
        "feeds": ["capstone"],
        "build": ["1 design aloud", "1 STAR aloud", "Capstone demo"],
        "doneWhen": ["Self-score in wave-1-checklist.md"],
    },
    {
        "title": "Apply tracker — 3 targets",
        "theme": "Target companies",
        "learn": "AI Systems / agentic ops / internal AI platform roles",
        "competency": "portfolio",
        "path": "interview-prep/answers/wave-1-checklist.md",
        "feeds": ["capstone"],
        "build": ["Company research", "Tailored resume bullets"],
        "doneWhen": ["3 companies documented"],
    },
    {
        "title": "Submit applications",
        "theme": "Submit applications",
        "learn": "Apply with portfolio links (dashboard + capstone + Okta IaC)",
        "competency": "portfolio",
        "path": "interview-prep/",
        "feeds": ["capstone"],
        "build": ["1+ applications", "Outreach"],
        "doneWhen": ["Apply log updated"],
    },
    {
        "title": "Program retro",
        "theme": "Program retro",
        "learn": "What elevated positioning; next-quarter hardening",
        "competency": "portfolio",
        "path": "study-notes/",
        "feeds": ["capstone"],
        "build": ["study-notes/program-retro.md"],
        "doneWhen": ["Retro + next quarter plan"],
    },
    {
        "title": "Maintain cadence",
        "theme": "Keep-alive",
        "learn": "Re-run evals; terraform plan clean on sandbox; keep capstone runnable",
        "competency": "portfolio",
        "path": "projects/08-capstone-ops-agent/",
        "feeds": ["capstone", "M8"],
        "build": ["Re-run evals", "terraform plan on 11-okta-iac sandbox", "Keep capstone runnable"],
        "doneWhen": ["Capstone runs", "Okta plan clean or drift notes", "Next milestone set"],
    },
]


def get_week_plan(week: int) -> dict | None:
    if 1 <= week <= 20:
        p = MINI_PROJECTS[week - 1]
        return {
            "title": p["title"],
            "theme": p.get("theme", p["title"]),
            "learn": p.get("learn", ""),
            "miniProject": p,
            "phase": "mini",
            "competency": p["competency"],
            "feeds": p.get("feeds", []),
        }
    if 21 <= week <= 24:
        p = CAPSTONE_WEEKS[week - 21]
        return {
            "title": p["title"],
            "theme": p.get("theme", p["title"]),
            "learn": p.get("learn", ""),
            "miniProject": p,
            "phase": "capstone",
            "competency": p["competency"],
            "feeds": p.get("feeds", []),
        }
    if 25 <= week <= 36:
        p = PORTFOLIO_WEEKS[week - 25]
        return {
            "title": p["title"],
            "theme": p.get("theme", p["title"]),
            "learn": p.get("learn", ""),
            "miniProject": p,
            "phase": "portfolio",
            "competency": p["competency"],
            "feeds": p.get("feeds", []),
        }
    return None
